question_data = [
    {"text": "The sky is blue.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "Humans have 4 senses.", "answer": "False"},
    {"text": "Water boils at 100 degrees Celsius.", "answer": "True"},
    {"text": "The Earth is flat.", "answer": "False"},
    {"text": "The chemical symbol for gold is Au.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "Venus is the closest planet to the Sun.", "answer": "False"},
    {"text": "Sound travels faster than light.", "answer": "False"},
    {"text": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
    {"text": "Lightning never strikes in the same place twice.", "answer": "False"},
    {"text": "The human nose can detect about 1 trillion different scents.", "answer": "True"},
    {"text": "Goldfish have a three-second memory.", "answer": "False"},
    {"text": "There are 365 days in a leap year.", "answer": "False"},
    {"text": "Adults have fewer bones than babies.", "answer": "True"},
    {"text": "Dolphins are fish.", "answer": "False"},
    {"text": "Coffee is a fruit.", "answer": "True"},
    {"text": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"text": "There are seven continents in the world.", "answer": "True"},
    {"text": "Light travels in straight lines.", "answer": "True"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "The human heart has four chambers.", "answer": "True"},
    {"text": "Bees can only sting once.", "answer": "False"},
    {"text": "The longest river in the world is the Nile.", "answer": "True"},
    {"text": "There are 10 planets in our solar system.", "answer": "False"},
    {"text": "Birds are warm-blooded animals.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "Humans can breathe and swallow at the same time.", "answer": "False"},
    {"text": "Ostriches can fly.", "answer": "False"},
    {"text": "The chemical symbol for iron is Fe.", "answer": "True"},
    {"text": "The capital of Japan is Beijing.", "answer": "False"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "Sound travels faster in water than in air.", "answer": "True"},
    {"text": "The human brain is fully developed by the age of 18.", "answer": "False"},
    {"text": "Polar bears are native to Antarctica.", "answer": "False"},
    {"text": "Tomatoes are vegetables.", "answer": "False"},
    {"text": "The Great Wall of China is longer than the distance between London and Beijing.", "answer": "True"},
    {"text": "Light is a form of energy.", "answer": "True"},
    {"text": "Humans and dinosaurs coexisted.", "answer": "False"},
    {"text": "The Eiffel Tower is in Berlin.", "answer": "False"},
    {"text": "An octopus has eight legs.", "answer": "False"},
    {"text": "Lightning can strike the same place twice.", "answer": "True"},
    {"text": "A leap year has 366 days.", "answer": "True"},
    {"text": "The largest organ in the human body is the liver.", "answer": "False"},
    {"text": "Whales are mammals.", "answer": "True"},
    {"text": "The Great Wall of China is made of one continuous wall.", "answer": "False"},
    {"text": "Electric eels are not true eels.", "answer": "True"},
    {"text": "Humans can see ultraviolet light.", "answer": "False"}
]